### ISSUE TITLE
R2 path error

### ISSUE THREAD

**Issue by shmilyin** [Cherry/ShareX-R2-Cloudflare-Workers#5]
in here, when now is July 2022, but zhe path in R2 is 2022/06
 ```
const folder = `${date.getFullYear()}/${('0' + date.getMonth()).slice(-2)}`;
```

**Comment by Cherry** [comment]
Fixed in https://github.com/Cherry/ShareX-R2-Cloudflare-Workers/commit/b0e2f260b00a8f8b7c4a4e2404553c1292489a50. 

Thanks!
