### ISSUE TITLE
Custom uploader URL parameters value should use curly braces in ShareX v1.4.1

### ISSUE THREAD

**Issue by ak1ra-komj** [Cherry/ShareX-R2-Cloudflare-Workers#7]
Hi,

Custom uploader URL parameters value should use curly braces in ShareX v1.4.1, `filename` should be `{filename}`, response `URL` should be `{json:image}`.

ref: https://getsharex.com/docs/custom-uploader#filename

**Comment by Cherry** [comment]
Thanks for submitting this issue! Closed as of #8
